version: "3"
services:
  humble-master:
    image: humble:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /c/Users/USERNAME_PLACEHOLDER/ros2_ws:/home/arece/ros2_ws
    stdin_open: true 
    tty: true
    DEVICE_PLACEHOLDER
