version: "3"
services:
  humble-master:
    image: humble:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/arthur/ros2_ws:/home/arthur/ros2_ws
    stdin_open: true 
    tty: true
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/card1:/dev/dri/card1"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
