version: "3"
services:
  humble-master:
    image: humble:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - C:\Users\esteb\ros2_ws;C:\Program Files\Git\home\arece\ros2_ws
    stdin_open: true 
    tty: true
